import os
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime

def generate_report(result, file_path=None):
    # =========================
    # 🛠️ SETUP & PATHS
    # =========================
    styles = getSampleStyleSheet()
    os.makedirs("data/reports", exist_ok=True)
    
    if file_path is None:
        label = result.get("label", "Condition").replace(" ", "_")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        file_path = f"data/reports/DermaSmart_{label}_{timestamp}.pdf"

    doc = SimpleDocTemplate(file_path, pagesize=A4)
    content = []

    # =========================
    # 🧾 TITLE & HEADER
    # =========================
    content.append(Paragraph("DermaSmart AI - Medical Analysis Report", styles["Title"]))
    content.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles["Normal"]))
    content.append(Spacer(1, 24))

    # =========================
    # 📊 PRIMARY ANALYSIS
    # =========================
    label = result.get("label", "Unknown Condition")
    conf = result.get("confidence", 0)
    conf_val = int(conf * 100) if conf <= 1.0 else int(conf)

    content.append(Paragraph(f"<b>Detected Condition:</b> {label}", styles["Heading2"]))
    content.append(Paragraph(f"<b>AI Confidence Score:</b> {conf_val}%", styles["Normal"]))
    content.append(Spacer(1, 12))

    # =========================
    # ⚠️ RISK ASSESSMENT (Safe Get)
    # =========================
    risk = result.get("risk", {})
    content.append(Paragraph("<b>Risk Assessment</b>", styles["Heading3"]))
    content.append(Paragraph(f"Risk Level: {risk.get('risk_level', 'Under Review')}", styles["Normal"]))
    content.append(Paragraph(f"Risk Score: {risk.get('risk_score', 0)}%", styles["Normal"]))
    content.append(Paragraph(f"Clinical Note: {risk.get('risk_message', 'Analyzing patterns...')}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # =========================
    # 🔥 SEVERITY ANALYSIS (Safe Get)
    # =========================
    severity = result.get("severity", {})
    content.append(Paragraph("<b>Severity Analysis</b>", styles["Heading3"]))
    content.append(Paragraph(f"Level: {severity.get('severity_level', 'Standard')}", styles["Normal"]))
    content.append(Paragraph(f"Insight: {severity.get('severity_message', 'Baseline clinical indicators.')}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # =========================
    # 🚨 TRIAGE & ACTION
    # =========================
    triage = result.get("triage", {})
    content.append(Paragraph("<b>Priority & Action Protocol</b>", styles["Heading3"]))
    content.append(Paragraph(f"Priority: {triage.get('priority', 'Routine')}", styles["Normal"]))
    content.append(Paragraph(f"Required Action: {triage.get('action', 'Consult a healthcare provider.')}", styles["Normal"]))
    content.append(Spacer(1, 12))

    # =========================
    # 🧬 FEATURES & RECOMMENDATIONS
    # =========================
    features = result.get("features", [])
    if features:
        content.append(Paragraph("<b>Detected Morphological Features</b>", styles["Heading3"]))
        for f in features:
            content.append(Paragraph(f"• {f}", styles["Normal"]))
        content.append(Spacer(1, 12))

    recs = result.get("recommendations", [])
    if recs:
        content.append(Paragraph("<b>Management Recommendations</b>", styles["Heading3"]))
        for rec in recs:
            content.append(Paragraph(f"• {rec}", styles["Normal"]))
        content.append(Spacer(1, 12))

    # =========================
    # 🔍 OTHER POSSIBILITIES
    # =========================
    top_results = result.get("top_results", [])
    if len(top_results) > 1:
        content.append(Paragraph("<b>Differential Diagnosis (Top Matches)</b>", styles["Heading3"]))
        for alt_label, score in top_results:
            alt_score = int(score * 100) if score <= 1.0 else int(score)
            content.append(Paragraph(f"• {alt_label}: {alt_score}% match", styles["Normal"]))
        content.append(Spacer(1, 12))

    # =========================
    # ⚠️ DISCLAIMER (IMPORTANT)
    # =========================
    content.append(Spacer(1, 20))
    disclaimer_style = styles["Normal"]
    content.append(Paragraph("<b>⚠️ MEDICAL DISCLAIMER:</b>", disclaimer_style))
    content.append(Paragraph(
        "This report is generated by an Artificial Intelligence system for informational purposes only. "
        "It does NOT constitute a formal medical diagnosis, prognosis, or treatment plan. "
        "Clinical findings should be verified by a licensed dermatologist or medical professional. "
        "If you are experiencing a medical emergency, please contact local emergency services immediately.",
        disclaimer_style
    ))

    # =========================
    # 📄 BUILD PDF
    # =========================
    try:
        doc.build(content)
        return file_path
    except Exception as e:
        print(f"Error building PDF: {e}")
        return None